### ISSUE TITLE
Naming the output file.

### ISSUE THREAD

**Issue by Imarie** [data-chirps/cross-words#1]
# Expected Behavior

Give either a path or a file name to the parameter output_path of xwords.generate.

# Current Behavior

I am not able to give a name to my output file. 'xwords.generate' automatically considers that it will ouput the result in training.md in whichever path was used (and could erase previous outputs).

## Steps to Reproduce

1. generate some output
`xwords.generate('my_input.txt',output_path='./my_ouptut.md')`
2. print from console
`131 sentences generated`
`131 objects written in file ./my_ouptut.mdtraining.md`
3. you get it...

Thank you !

**Comment by mkoa** [comment]
Functionnality has been added with commit ec5cf56a471068efc6d7cf79624b1206a7c0bc42
